global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'flink'
  static_configs:
    - targets: ['jobmanager:9249', 'taskmanager:9250']

- job_name: 'kafka'
  static_configs:
    - targets: ['kafka-jmx-exporter:9404']

- job_name: 'spark'
  static_configs:
    - targets: ['spark-jmx-exporter:9405']

- job_name: 'postgres'
  static_configs:
    - targets: ['postgres-exporter:9187']

- job_name: 'api'
  static_configs:
    - targets: ['api:8001']
